export const allPets = [
  {
    id: 1,
    type: "Gato",
    name: "Cosmo",
    age: 0.3,
    description: "Soy amado por todos",
    url: "https://cdn2.thecatapi.com/images/20q.jpg",
  },
  {
    id: 2,
    type: "Gato",
    name: "Chapatin",
    age: 3,
    description: "Soy muy tranquilo",
    url: "https://cdn2.thecatapi.com/images/3ic.jpg",
  },
  {
    id: 3,
    type: "Gato",
    name: "Colita",
    age: 2,
    description: "Soy blanquita, pero mi colita es negra",
    url: "https://cdn2.thecatapi.com/images/9o6.jpg",
  },
  {
    id: 4,
    type: "Gato",
    name: "Kit y Kat",
    age: 3,
    description: "Vamos en dupla, tendras el doble de amor",
    url: "https://cdn2.thecatapi.com/images/a8b.jpg",
  },
  {
    id: 5,
    type: "Gato",
    name: "Yellow",
    age: 6,
    description: "Me gusta contemplar el mundo",
    url: "https://cdn2.thecatapi.com/images/agh.jpg",
  },
  {
    id: 6,
    type: "Gato",
    name: "Manchas",
    age: 0.4,
    description: "La blanquita es mi mamá",
    url: "https://cdn2.thecatapi.com/images/MTc3NDE5Nw.jpg",
  },
  {
    id: 7,
    type: "Gato",
    name: "Cazador",
    age: 2,
    description: "Que delicia comer",
    url: "https://cdn2.thecatapi.com/images/MTk3MjE1Mw.jpg",
  },
  {
    id: 8,
    type: "Gato",
    name: "Muñeco",
    age: 1.5,
    description: "No soy gato, soy panda",
    url: "https://cdn2.thecatapi.com/images/2uo.jpg",
  },
  {
    id: 9,
    type: "Gato",
    name: "Mesi",
    age: 0.7,
    description: "Soy el 10",
    url: "https://cdn2.thecatapi.com/images/at1.jpg",
  },
  {
    id: 10,
    type: "Gato",
    name: "Sam y Cat",
    age: 0.3,
    description: "Gemelitos inseparables",
    url: "https://cdn2.thecatapi.com/images/c31.jpg",
  },
  {
    id: 11,
    type: "Gato",
    name: "Intelectual",
    age: 7,
    description: "La literatura es mi pasión",
    url: "https://cdn2.thecatapi.com/images/cps.jpg",
  },
  {
    id: 12,
    type: "Gato",
    name: "Grey",
    age: 3.5,
    description: "Me encanto",
    url: "https://cdn2.thecatapi.com/images/cua.jpg",
  },
  {
    id: 13,
    type: "Gato",
    name: "Andy",
    age: 1,
    description: "Doy la manito",
    url: "https://cdn2.thecatapi.com/images/MTg3MjE2OQ.jpg",
  },
  {
    id: 14,
    type: "Gato",
    name: "Rayas",
    age: 1.5,
    description: "Debería llamarme orejas",
    url: "https://cdn2.thecatapi.com/images/DmP9GCClC.jpg",
    
  },
  {
    id: 15,
    type: "Gato",
    name: "Pelos",
    age: 0.5,
    description: "Soy así y así seguire",
    url: "https://cdn2.thecatapi.com/images/aKbsEYjSl.jpg",
    }
];
